version: "3"

services:

  cifv3:
    container_name: cifv3
    image: cifv3
    ports:
      - "5000:5000/tcp"
      #- "8443:443/tcp"
    depends_on:
      - elasticsearch
    environment:
      CIF_TOKEN: 'foo'
      CIF_HUNTER_TOKEN: 'bar'
      CSIRTG_SMRT_TOKEN: 'baz'
      CIF_HTTPD_TOKEN: 'boo'
      CIF_STORE_STORE: 'elasticsearch'
      CIF_STORE_NODES: 'elasticsearch:9200'
      CIF_STORE_ES_UPSERT_MODE: 1
      #CIF_HTTPD_LISTEN: '0.0.0.0'
      #SERVICE_STOP_SMRT: 1
      #DOCKER_HTTPS: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch_mini
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 30s
        timeout: 10s
        retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 127.0.0.1:9200:9200
