---
- hosts: all

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  vars:
    router_hunter_token: '1234'
#    smrt_cif_remote: https://localhost
#    smrt_cif_token: '1234'

#    router_enabled: false  # smrt only role
#    smrt_enabled: false   # router only role

  tasks:
    - include_tasks: tasks/main.yml