#!/usr/bin/with-contenv sh

export CIF_LOGLEVEL=DEBUG
export CIF_RUNTIME_PATH="/home/cif/run/"
export CIF_DATA_PATH="/var/lib/cif"
export CIF_STORE_STORE="sqlite"
#export CIF_STORE_NODES="localhost:9200"
export CIF_ROUTER_CONFIG_PATH="/etc/cif/cif-router.yml"
export CIF_HUNTER_EXCLUDE="osint.bambenekconsulting.com:dga"
export CIF_HUNTER_THREADS=""
export CIF_GATHERER_THREADS="2"
export CIF_HUNTER_ADVANCED=""
export CIFSDK_CLIENT_ZEROMQ_FIREBALL_SIZE="500"
#export CIF_HTTPD_LISTEN="127.0.0.1"
#export CIF_HTTPD_TOKEN=""
#export CIF_HTTPD_PROXY=0
export CIF_STORE_TRACE=0
export CIF_ROUTER_TRACE=0
export CIF_HUNTER_TRACE=0
#export CIF_HTTPD_TRACE=0
#export CIF_STORE_ES_UPSERT_MODE=1
#export CIF_STORE_ES_UPSERT_TRACE=1
#CIF_STORE_ES_TRACE=0
#CIF_STORE_SQLITE_TRACE=0

export PATH="/cif_venv/bin:${PATH}"
export HOME="/home/cif"
cd ${HOME}

s6-setuidgid cif cif-router --config=/etc/cif/cif-router.yml

