#!/command/with-contenv bash

export CIF_RUNTIME_PATH="/home/cif/run/"
export CIF_DATA_PATH="/var/lib/cif"
export CIF_HTTPD_TOKEN="${CIF_HTTPD_TOKEN:-bar}"
export CIF_HTTPD_PROXY=0
export CIF_HTTPD_TRACE=0
export CIF_HTTPD_GUNICORN_WORKERS="${CIF_HTTPD_GUNICORN_WORKERS:-4}"
export CIF_HTTPD_GUNICORN_GTIMEOUT="${CIF_HTTPD_GUNICORN_GTIMEOUT:-120}"
export CIF_HTTPD_GUNICORN_TIMEOUT="${CIF_HTTPD_GUNICORN_TIMEOUT:-150}"
export CIF_HTTPD_GUNICORN_KEEPALIVE="${CIF_HTTPD_GUNICORN_KEEPALIVE:-30}"
export CIF_HTTPD_GUNICORN_MAXREQUESTS="${CIF_HTTPD_GUNICORN_MAXREQUESTS:-25}"
export CIF_HTTPD_GUNICORN_LOG_LEVEL="${CIF_HTTPD_GUNICORN_LOG_LEVEL:-INFO}"


if [ -z ${CIF_HTTPD_LISTEN} ]
then
  export CIF_HTTPD_LISTEN="127.0.0.1"
else
  export CIF_HTTPD_LISTEN="${CIF_HTTPD_LISTEN}"
fi

export PATH="/cif_venv/bin:${PATH}"
export HOME="/home/cif"
cd ${HOME}

/command/s6-setuidgid cif gunicorn \
  -w ${CIF_HTTPD_GUNICORN_WORKERS} \
  --max-requests-jitter 5 \
  -b ${CIF_HTTPD_LISTEN}:5000 \
  cif.httpd:app \
  --worker-class gevent \
  --preload \
  --max-requests ${CIF_HTTPD_GUNICORN_MAXREQUESTS} \
  --graceful-timeout ${CIF_HTTPD_GUNICORN_GTIMEOUT} \
  --keep-alive ${CIF_HTTPD_GUNICORN_KEEPALIVE} \
  --timeout ${CIF_HTTPD_GUNICORN_TIMEOUT} \
  --log-level ${CIF_HTTPD_GUNICORN_LOG_LEVEL}

#-------------------------------
# available env vars

# httpd
#export CIF_HTTPD_LIMIT_MINUTE
#export CIF_HTTPD_LISTEN
#export CIF_HTTPD_LISTEN_PORT
#export CIF_HTTPD_PIDFILE
#export CIF_HTTPD_PROXY
#export CIF_HTTPD_SECRET_KEY
#export CIF_HTTPD_TRACE=1
#export CIF_HTTPD_UI_HOSTS
#export CIF_ROUTER_ADDR
