---
- name: "Check for version 18.04"
  fail: msg="Must be version 18.04 or higher"
  when: ansible_distribution_version is version_compare('18.04', '<')

- include_tasks: firewall.yml
  when: DOCKER_BUILD is undefined or DOCKER_BUILD == 'no' or DOCKER_BUILD == ""
  tags: firewall

- include_tasks: deps.yml
  tags: deps

- include_tasks: unattended_updates.yml
  tags: deps
