---
- name: "Check for version 16.04"
  fail: msg="Must be version 16.04 or higher"
  when: ansible_distribution_version | version_compare('16.04', '<')

- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - build-essential
    - python3-dev
    - python3-minimal
    - python3-pip
    - python3-venv
    - python3-virtualenv
    - python-virtualenv
    - sqlite3