#!/usr/bin/with-contenv sh

if [ -n "${DOCKER_NO_SMRT}" ]
then
  while true; do sleep 1; done
fi

if [ -z "${CSIRTG_LOGLEVEL}" ]
then
  export CSIRTG_LOGLEVEL=INFO
else
  export CSIRTG_LOGLEVEL="${CSIRTG_LOGLEVEL}"
fi

export CSIRTG_SMRT_RUNTIME_PATH=/var/run/smrt
export CSIRTG_SMRT_RULES_PATH=/etc/cif/rules/default
export CSIRTG_SMRT_CACHE_PATH=/var/lib/smrt
export CSIRTG_SMRT_FIREBALL_SIZE=500
export CSIRTG_SMRT_GOBACK_DAYS=3
#
#CIF_TOKEN=
#CIF_REMOTE=
#CSIRTG_TOKEN=
#

export PATH="/cif_venv/bin:${PATH}"
export HOME="/home/cif"
cd ${HOME}

s6-setuidgid cif csirtg-smrt --remember --service --client cif --fireball --delay 5 --config /etc/cif/csirtg-smrt.yml
