#!/command/with-contenv bash

export CIF_LOGLEVEL=DEBUG
export CIF_RUNTIME_PATH="/home/cif/run/"
export CIF_DATA_PATH="/var/lib/cif"
export CIF_HTTPD_TOKEN=""
export CIF_HTTPD_PROXY=0
export CIF_HTTPD_TRACE=0

if [ -z ${CIF_HTTPD_LISTEN} ]
then
  export CIF_HTTPD_LISTEN="127.0.0.1"
else
  export CIF_HTTPD_LISTEN="${CIF_HTTPD_LISTEN}"
fi

export PATH="/cif_venv/bin:${PATH}"
export HOME="/home/cif"
cd ${HOME}

/command/s6-setuidgid cif gunicorn \
  -w 4 \
  --max-requests-jitter 5 \
  -b ${CIF_HTTPD_LISTEN}:5000 \
  cif.httpd:app \
  --worker-class gevent \
  --max-requests 25 \
  --graceful-timeout 60

#-------------------------------
# available env vars

# httpd
#export CIF_HTTPD_LIMIT_MINUTE
#export CIF_HTTPD_LISTEN
#export CIF_HTTPD_LISTEN_PORT
#export CIF_HTTPD_PIDFILE
#export CIF_HTTPD_PROXY
#export CIF_HTTPD_SECRET_KEY
#export CIF_HTTPD_TRACE=1
#export CIF_HTTPD_UI_HOSTS
#export CIF_ROUTER_ADDR
