---
- name: install versioneer
  pip: name="{{ item }}"
  with_items: [ versioneer markupsafe ]

- name: cleaning up dist
  local_action: file path={{ cif_build_sdist }}/dist state=absent

- name: build dist
  local_action: shell python setup.py sdist chdir={{ cif_build_sdist }}/

- name: find dist name
  local_action: find paths={{ cif_build_sdist }}/dist patterns="^(cif\-.*\.tar.gz)$" use_regex=True
  register: p

- name: upload dist and uarchive
  unarchive: src={{ p.files[0].path }} dest=/tmp

- name: find dist name
  find: paths=/tmp patterns="^(cif-.*)$" use_regex=True file_type=directory
  register: p

- name: install requirements
  command: pip install -r dev_requirements.txt chdir="{{ p.files[0].path }}"
  become: yes

- name: run tests
  command: python setup.py test chdir="{{ p.files[0].path }}"
  become: yes

- name: install cif
  command: python setup.py install chdir="{{ p.files[0].path }}"
  environment:
    CIF_ENABLE_INSTALL: 1
  become: yes
