---
- name: "Check for version 22.04"
  fail: msg="Must be version 22.04 or higher"
  when: ansible_distribution_version is version_compare('22.04', '<')

- name: install deps
  apt:
    state: latest
    pkg: 
      - build-essential
      - python3-dev
      - python3-minimal
      - python3-pip
      - python3-venv
      - python3-virtualenv
      - sqlite3
